ifndef LIBPOSIX_SIGNALS_INCLUDE
LIBPOSIX_SIGNALS_INCLUDE := 1


LIBPOSIX_SIGNALS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

CFLAGS  += -I$(LIBPOSIX_SIGNALS_DIR)include
LDFLAGS += -L$(LIBPOSIX_SIGNALS_DIR)
LDLIBS  += -lposix-signals


endif 